New-ADOrganizationalUnit -Name "IT_Department" -Path "DC=lab,DC=local"
New-ADOrganizationalUnit -Name "HR_Department" -Path "DC=lab,DC=local"
New-ADOrganizationalUnit -Name "RedTeam" -Path "DC=lab,DC=local"
New-ADOrganizationalUnit -Name "BlueTeam" -Path "DC=lab,DC=local"
New-ADOrganizationalUnit -Name "TestOU" -Path "DC=lab,DC=local"